### ISSUE TITLE
Migrate to Legend-State 2.0

### ISSUE THREAD

**Issue by bouzidanas** [bezda-team/rhp#1]
# Overview
Rhp currently uses the [Legend-State 1.0](https://legendapp.com/open-source/legend-state-v1/) state library for state management. 
The motivations behind migrating to Legend-State 2.0 include
- keeping rhp up to date
- better support. Legend-State 1.0 support and resources (including documentation) might no longer be maintained, updated
- incorporate performance improvements. Legend-State 2.0 brings improvements such as:
  - Version 2.0 removes old deprecated features to reduce bundle size
  - observable nodes are now created on demand as you access them so there's no longer any performance cost to creating or setting observables with big objects
  - there's no longer any issues with putting large/recursive objects like DOM elements in state

## Comments
On the aforementioned improvement
>there's no longer any issues with putting large/recursive objects like DOM elements in state

This could potentially resolve an issue where sometimes the use of `opaqueObject` is needed to avoid Legend-States issue with circular references inside observables. It seems that this issue can even arise in the common scenerio where an object given to an observable contains multiple references to the same object. For example, changes like this are sometimes required:
```diff
//your tsx file
import { observable, opaqueObject } from '@legendapp/state';
import type { Observable } from '@legendapp/state';

const myColor = "#222222"

// Create observable 
- const mybservable = observable({a: myColor, b: 2, c: myColor});
+ const mybservable = observable({a: myColor, b: 2, c: opaqueObject(myColor)});
```

# Todo
The following tasks are obtained or derived from the [migration guide](https://legendapp.com/open-source/state/other/migrating/) provided in the Legend-State documentation.
- [ ] Switch to Legend-State version 1.11 to display deprecation warnings to 
  - help determine what changes need to be made
  - verify changes made are sufficient/complete
- [ ] Replace depreciated `use` function calls with `useSelector`
Example:
```diff
- import { enableReactUse } from '@legendapp/state/config/enableReactUse';
+ import { useSelector } from '@legendapp/state/react';

- enableReactUse();

const Component = () => {
    // Create an observable object inside of a component
    const myLocalObservable = useObservable(1);

-    const currentMyObservableValue = myLocalObservable.use();
+    const currentMyObservableValue = useSelector(myLocalObservable);

    return <div>{currentMyObservableValue}</div>;
};
```
- [ ] Change `<For>` component's `item` prop name to `item$` 
- [ ]  Remove usage of enableLegendStateReact() or enableReactDirectRender() as well as any usage of direct rendering, and replace it with Memo
- [ ] Remove usage of other depreciated functions

# Resources
- [Legend-State docs](https://legendapp.com/open-source/state/intro/introduction/)
- [Legend-State migration guide](https://legendapp.com/open-source/state/other/migrating/)
- [Legend-State 2.0 blog post](https://legendapp.com/open-source/legend-state-v2/)
