### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by bouzidanas** [bezda-team/rhp#8]
Documentation needs to be consistent with documentation and include latest installation instructions and recommendations

# Todo

- [ ] update and simplify overview. Focus on what rhp is and what its for. Could look to Introduction section of docs for inspiration.
- [ ] add latest installation instructions
- [ ] add recommendations
- [ ] add simple start up test example (something like AnimatedDots)
- [ ] add MIT license
- [ ] link to better interactive examples from docs instead of current demo
- [ ] add contribution section
