### ISSUE TITLE
Allow writing templates in JSX style

### ISSUE THREAD

**Issue by bouzidanas** [bezda-team/rhp#9]
# Overview
Since template are things that tell certain components what it should include as its children, how these children should be organized hierarchically and how to configure them, it makes sense and might be more intuitive for some people to create templates in JSX style where the configuration information is provided in prop-value pairs and the type corresponds to the component name.

## Notes/comments

Note that since there is some logic (especially dealing with state-management) in choosing, constructing and setting up the components using the information in a template, it does not make sense to have the JSX be direct calls to the component functions of the components that will be added themselves. Thus, this JSX template's only purpose should be to provide the same information/content provided by the regular template objects currently being used. 

So, the general allure of this feature is that users/devs will be able to create and add templates in a natural and intuitive way that is more consistent appearance-wise with the rest of the process of creating plots with this component library.

# Implementation suggestions and ideas
Consider the mostly empty template object
```ts
    {
      type: "bar-content-container",
      elements: [
        {
          type: "bar-dec-container",
          elements: [
            {
              type: "bar",
              order: 0,
              CSS: "box-sizing: border-box; border-radius: 0 10px 10px 0;",
              markup: "<div style='background-color: {{color}};height:100%;width:100%;'></div>",
            },
            {
              type: "decoration",
              order: 1,
              useData: true,
              CSS: "height: 100%;",
              markup: "<div style='color: {{color}};'>{{$dataValue}}</div>",
            },
          ],
          CSS: "background: none;",
          decorationWidth: "52px",
          order: 1,
        }, 
      ],
      decorationWidth: "10%",
      order: 1,
    },
    {
      type: "decoration",
      order: 0,
      CSS: "height: 100%;",
      markup: "<span>{{bar-label}}</span>",
    }
```

and remember that the type property indicates what type of component to insert

| type  | &#8594; | component |
| --- | --- | --- |
| `"bar-content-container"` | &#8594; | `<BarContentContainer>` |
| `"bar-dec-container"` | &#8594; | `<BarDecContainer>` |
| `"decoration"` | &#8594; | `<Decoration>` |
| `"bar"` | &#8594; | `<Bar>` |

Furthermore, the nesting determines the structure of the component tree ie where the above components are inserted. For this component we have

\<ParentComponent>
- decoration (order: 0)
- bar-content-container (order: 1)
  - bar-dec-container (order: 0)
    - bar (order: 0)
    - decoration (order: 1)  
 
\</ParentComponent>

The JSX style template that is equivalent to the above might look like:

```ts
<ParentComponent>
    <Template>
        <DecorationTemplate order={0} css="height: 100%;" markup= "<span>{{bar-label}}</span>" />
        <BarContentTemplate order={1} decorationWidth="10%" >
            <BarDecTemplate order={1} css="background: none;" decorationWidth="52px" >
                <BarTemplate order={0} css="box-sizing: border-box; border-radius: 0 10px 10px 0;" markup="<div style='background-color: {{color}};height:100%;width:100%;'></div>" />
                <DecorationTemplate order={1}  css="height: 100%;"  markup="<div style='color: {{color}};'>{{$dataValue}}</div>" useData />
            </BarDecTemplate>
        </BarContentTemplate>
    </Template>
</ParentComponent>
```

# Tasks

- [x] add template shell/pseudo function components
- [x] create logic for converting a JSX template to an object template
- [x] determine which type of template should supersede or override when provided
  - [x] logic for incorporating defaults when JSX style template is used
- [x] test logic for converting a JSX template 
  - [ ] investigate performance tradeoffs
- [ ]  add logic to all components that use templates to construct/populate its children
